
export async function seed(knex): Promise<void> {
    await knex('users').del();

    await knex('users').insert([
        { firstname: 'Tsubasa', lastname: 'Ozora', email: 'tsubasa.ozora@meiwa.com', birthdate: '1985-06-15' },
        { firstname: 'Genzo', lastname: 'Wakabayashi', email: 'genzo.wakabayashi@meiwa.com', birthdate: '1986-03-01' },
        { firstname: 'Taro', lastname: 'Misaki', email: 'taro.misaki@meiwa.com', birthdate: '1985-09-17' },
        { firstname: 'Kojiro', lastname: 'Hyuga', email: 'kojiro.hyuga@meiwa.com', birthdate: '1985-05-01' },
        { firstname: 'Shun', lastname: 'Nitta', email: 'shun.nitta@meiwa.com', birthdate: '1985-07-07' },
        { firstname: 'Ryo', lastname: 'Sakuragi', email: 'ryo.sakuragi@meiwa.com', birthdate: '1986-02-18' },
        { firstname: 'Hikaru', lastname: 'Matsuyama', email: 'hikaru.matsuyama@meiwa.com', birthdate: '1985-12-23' },
        { firstname: 'Takeshi', lastname: 'Kira', email: 'takeshi.kira@meiwa.com', birthdate: '1986-11-10' },
        { firstname: 'Carlos', lastname: 'Santana', email: 'carlos.santana@mexico.com', birthdate: '1985-08-04' },
        { firstname: 'Julian', lastname: 'Ross', email: 'julian.ross@brazil.com', birthdate: '1986-04-06' },
        { firstname: 'Pierre', lastname: 'Tebow', email: 'pierre.tebow@france.com', birthdate: '1985-10-14' },
        { firstname: 'David', lastname: 'Samson', email: 'david.samson@england.com', birthdate: '1986-01-23' },
        { firstname: 'Victor', lastname: 'Aston', email: 'victor.aston@england.com', birthdate: '1985-12-11' },
        { firstname: 'Santiago', lastname: 'Hernandez', email: 'santiago.hernandez@spain.com', birthdate: '1985-05-30' },
        { firstname: 'Ricardo', lastname: 'Espadas', email: 'ricardo.espadas@spain.com', birthdate: '1986-09-22' },
        { firstname: 'Gianluca', lastname: 'Bertoni', email: 'gianluca.bertoni@italy.com', birthdate: '1985-02-02' },
        { firstname: 'Marco', lastname: 'Lupin', email: 'marco.lupin@italy.com', birthdate: '1986-05-15' },
        { firstname: 'Antonio', lastname: 'Ricci', email: 'antonio.ricci@italy.com', birthdate: '1985-03-23' },
        { firstname: 'Masao', lastname: 'Sano', email: 'masao.sano@meiwa.com', birthdate: '1985-04-04' },
        { firstname: 'Ken', lastname: 'Perry', email: 'ken.perry@brazil.com', birthdate: '1986-08-29' },
        { firstname: 'Jorge', lastname: 'Costa', email: 'jorge.costa@portugal.com', birthdate: '1986-07-15' },
        { firstname: 'Rafael', lastname: 'Lima', email: 'rafael.lima@brazil.com', birthdate: '1985-11-11' },
        { firstname: 'Satoru', lastname: 'Kuroda', email: 'satoru.kuroda@meiwa.com', birthdate: '1986-10-20' },
        { firstname: 'Tatsuya', lastname: 'Sakamoto', email: 'tatsuya.sakamoto@meiwa.com', birthdate: '1985-06-05' },
        { firstname: 'Koji', lastname: 'Kusama', email: 'koji.kusama@meiwa.com', birthdate: '1986-09-03' },
        { firstname: 'Tetsuo', lastname: 'Sano', email: 'tetsuo.sano@meiwa.com', birthdate: '1985-01-13' },
        { firstname: 'Takaaki', lastname: 'Takanori', email: 'takaaki.takanori@meiwa.com', birthdate: '1986-12-08' },
        { firstname: 'Taro', lastname: 'Takahashi', email: 'taro.takahashi@meiwa.com', birthdate: '1985-02-14' },
        { firstname: 'Kyo', lastname: 'Kurama', email: 'kyo.kurama@meiwa.com', birthdate: '1985-09-18' },
        { firstname: 'Hiroshi', lastname: 'Yamamoto', email: 'hiroshi.yamamoto@meiwa.com', birthdate: '1985-10-02' },
        { firstname: 'Riki', lastname: 'Koyama', email: 'riki.koyama@meiwa.com', birthdate: '1986-11-26' },
        { firstname: 'Yuto', lastname: 'Yamashita', email: 'yuto.yamashita@meiwa.com', birthdate: '1985-03-07' },
        { firstname: 'Tetsuya', lastname: 'Seki', email: 'tetsuya.seki@meiwa.com', birthdate: '1986-04-12' },
        { firstname: 'Takahiro', lastname: 'Fujita', email: 'takahiro.fujita@meiwa.com', birthdate: '1985-01-21' },
        { firstname: 'Kazuya', lastname: 'Tsunoda', email: 'kazuya.tsunoda@meiwa.com', birthdate: '1986-06-18' },
        { firstname: 'Souta', lastname: 'Nakagawa', email: 'souta.nakagawa@meiwa.com', birthdate: '1985-02-11' },
        { firstname: 'Ryoji', lastname: 'Kurata', email: 'ryoji.kurata@meiwa.com', birthdate: '1986-10-01' },
        { firstname: 'Shigeo', lastname: 'Nakata', email: 'shigeo.nakata@meiwa.com', birthdate: '1985-05-21' },
        { firstname: 'Hiroki', lastname: 'Tada', email: 'hiroki.tada@meiwa.com', birthdate: '1986-08-10' },
        { firstname: 'Kenta', lastname: 'Nakamura', email: 'kenta.nakamura@meiwa.com', birthdate: '1985-03-14' },
        { firstname: 'Keisuke', lastname: 'Kobayashi', email: 'keisuke.kobayashi@meiwa.com', birthdate: '1986-02-26' },
        { firstname: 'Atsushi', lastname: 'Matsumoto', email: 'atsushi.matsumoto@meiwa.com', birthdate: '1985-08-01' },
        { firstname: 'Shinji', lastname: 'Okada', email: 'shinji.okada@meiwa.com', birthdate: '1986-07-11' },
        { firstname: 'Issei', lastname: 'Uchida', email: 'issei.uchida@meiwa.com', birthdate: '1985-12-13' },
        { firstname: 'Yusuke', lastname: 'Ishida', email: 'yusuke.ishida@meiwa.com', birthdate: '1986-11-19' },
        { firstname: 'Kiyotaka', lastname: 'Nakano', email: 'kiyotaka.nakano@meiwa.com', birthdate: '1985-04-23' },
        { firstname: 'Keiji', lastname: 'Kida', email: 'keiji.kida@meiwa.com', birthdate: '1986-01-29' },
        { firstname: 'Jiro', lastname: 'Nishida', email: 'jiro.nishida@meiwa.com', birthdate: '1985-07-19' },
        { firstname: 'Takumi', lastname: 'Saito', email: 'takumi.saito@meiwa.com', birthdate: '1986-03-11' },
        { firstname: 'Yuji', lastname: 'Inoue', email: 'yuji.inoue@meiwa.com', birthdate: '1985-10-25' },
        { firstname: 'Ryo', lastname: 'Ishikawa', email: 'ryo.ishikawa@meiwa.com', birthdate: '1986-05-06' },
        { firstname: 'Kazuo', lastname: 'Miya', email: 'kazuo.miya@meiwa.com', birthdate: '1985-11-22' }
    ]);
};
